nama= "Fatimah Nazwa Siregar"
nim= "0110124217"
rombel= "SI06"
no_telp="082287250852"
alamat= "simpang lansek kadok"

print(f"nama saya adalah : {nama}")
print(f"nim saya adalah : {nim}")
print(f"rombel saya adalah:{rombel}")
print(f"NO telepon saya adalah:{no_telp}")
print(f"alamat saya di:{alamat}")
print("===============")


#Soal nomor 2
nama= " Salwa salesyia putri"
nim= "0110124155"
rombel="SI06"
no_telp="0881025570519"
alamat="Bogor"

print(f"nama saya adalah:{nama}")
print(f"nim saya adalah:{nim}")
print(f"rombel saya adalah:{rombel}")
print(f"no telepon saya adalah:{no_telp}")
print(f"alamat saya di:{alamat}")
print("=====================")
      

#SOAL NOMOR 3

TB= int(input("Masukkan tinggi badan"))
bb_ideal= (TB- 100) - (TB- 100) * 0,15

print("berat badan ideal adalah:",bb_ideal)
print("========================")

#SOAL NOMOR 4
celcius= float(input("Masukkan nilai celcius:"))
fahrenheit= 9/5 *celcius + 32

print(f"suhu dalam fahreinhet adalah:{fahrenheit:}")
print("=======================")

#SOAL NOMOR 5
r= int(input("Masukkan jari-jari"))
t= int(input("Maukkan tinggi"))
la= int(input("Maukkan luas alas"))
ka= int(input("Masukkan keliling alas"))
phi= 22/7
luas= (2 * la) + (ka * t)
keliling= phi * phi * r 

print("luas tabung adalah=", luas)
print( "keliling tabung adalah=", keliling)

print(1+2)






 